<?php
    use ObjectivePHP\Application\Session\Session;
    use ObjectivePHP\Application\View\Helper\Vars;
    use ObjectivePHP\Html\Tag\Tag;
    use ObjectivePHP\Notification\MessageInterface;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?= Vars::config()->app->name . ' / Showcase' ?></title>

    <!-- Bootstrap core CSS -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/theme.css" rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body role="document">

<?php include __DIR__ .'/partials/navbar.phtml'; ?>

<div class="container theme-showcase" role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <h1>
            <?= Vars::get('page.title') ?>
                <br />
            <?= Vars::string('page.subtitle')->prepend('<small>')->append('</small>') ?>
        </h1>
        <p></p>
    </div>
    <?php include __DIR__ . '/partials/notifications.phtml'; ?>
    <div>
        <?= Vars::get('view.output') ?>
    </div>
</div>
<!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/js/jquery.min.js"></script>
<script src="/bootstrap/js/bootstrap.min.js"></script>

</body>
</html>
