<?php
use ObjectivePHP\Application\Config\ApplicationName;
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title><?= $this->param(ApplicationName::KEY) ?></title>

        <link href="/style.css" rel="stylesheet">
    </head>
    <body role="document">
        <?php include __DIR__ . '/partials/navbar.phtml'; ?>

        <?= $this->getViewOutput();  ?>

        <script src="/theme.js"></script>
    </body>
</html>

