<?php
use ObjectivePHP\Application\Config\ApplicationName;
use ObjectivePHP\Application\View\Helper\Vars;
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title><?= Vars::config()->get(ApplicationName::class) . ' / ' . Vars::get('page.title') ?></title>

        <link href="/style.css" rel="stylesheet">
    </head>
    <body role="document">
        <?php include __DIR__ . '/partials/navbar.phtml'; ?>

        <?php include __DIR__ . '/partials/notifications.phtml'; ?>

        <?= Vars::get('view.output')  ?>

        <script src="/theme.js"></script>
    </body>
</html>

