<?php

use ObjectivePHP\Application\Config\ApplicationName;

?>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/">
        <img src="/img/brand.png" width="30" height="30" class="d-inline-block align-top" alt="">
        <?= $this->param(ApplicationName::KEY) ?>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/example">Other Page</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/info" target="_blank">PHP Info</a>
            </li>
        </ul>
        <ul class="navbar-nav my-2 my-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="http://github.com/objective-php" target="_blank">Objective PHP on GitHub</a>
            </li>
        </ul>
    </div>
</nav>
